sudo: false
language: node_js
node_js:
- 8
before_script:
- npm i
script:
- npm run test
- npm run build
cache:
  directories:
  - node_modules
aliases:
  deploy: &deploy
    provider: heroku
    api_key: &1
      secure: TTTqmMK0Ommfp4HBEJKysuptbErKlg2v86CbOGCz0Sn7btw7auGMdocBjzs6Y40VCEcxtek1VQ0uVlPyp5xx/exGRp2SF1LK77aPB7IH1tF/GAWBN1UvbYmpyPvh7wYggu8UBvWRJHSLRtp2ofrBQ0p5aq11XIgfIxsf0Yck927sgtT5+jVwbTnPDclxTI1ccVRZY672zRA3UFlqSE/FgHhsSDc/JrFngbDmSyJPOZo7JMqiCox3y9mE6OyFmhriTALL9TqV6+dgnRUAK8RHsW1hN28BybhHc/sALC0vGW/0XUzDTyw/jhwRtOt826olbda8geWwsdeO7iYgxnAdwLj5ymiHIjbSOM7TVo4ajaxji/JnvZKS3hqgFJ3iFXKwe19us3lgRbzHizigi1zwRH7FoGbz8I0/Hq0DAQ4S6gmq2jvRlqC0qK5v/WrQjNfLBk/c8G5X/vWtE3gqjkD2wndG892vr6Z7WTIcdGq8PyhQIzCMb9giKdVhX3oLwiqeyXjIDfEceGtJbsVUW0ysdI4o9Ch8RSZ2UdUC/YVhqAYNUR2KwrG+Jo76QWFuppLcjcMWwpagsDV//704q4+TAPgMYU81jducRfkvM2JnMSrGsjYcxJ7sFf6WIjUYaZ8gWYECopNAU+WJQx2KuJZIkK2q32uIPT85t6HwPBc+1Y0=
    skip_cleanup: true
jobs:
  include:
  - stage: Deploy (development)
    if: tag IS blank
    deploy:
      <<: *deploy
      app: ya-git-dev
      on:
        all_branches: true
  - stage: Deploy (production)
    if: tag IS present
    deploy:
      <<: *deploy
      app: ya-git-prod
      on:
        tags: true
        all_branches: true
