sudo: required
language: node_js

node_js:
 - 'node'
 - 8

install:
 - npm install

script:
 - npm run lint
 - npm run build

services:
 - docker

 deploy:
  provider: heroku
  api_key:
    secure: ""
